<a href="https://colab.research.google.com/github/jcmoralest/ICESI_AalisisDatos1_PSmart/blob/main/Taller_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Pregunta SMART-Ajustada: identificar cuales son las variables que generan mayor impacto en el buro de crédito de Colombia para ayudar a las personas a mejorar su puntaje crediticio.

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Cargar el dataset
df = pd.read_csv('datos_buro_T3.csv')

df.head(5000)

,index,Edad,Género,Ingreso_mensual,Saldo_total,Número_de_cuentas,Historial_crediticio,Tipo_de_empleo,Porcentaje_uso_credito,Mora_en_pagos,Número_de_moras,Monto_total_prestado,Puntaje_crediticio
0,0,63,Femenino,1995089,9864628,5,12,Independiente,0.551613,Sí,4,11261919,494
1,1,53,Femenino,4063724,4092912,4,19,Desempleado,0.391506,Sí,4,190549,309
2,2,23,Femenino,5210231,18200066,4,9,Desempleado,0.606219,No,6,29633064,563
3,3,22,Femenino,9404231,6860855,1,14,Desempleado,0.605031,No,3,33700465,389
4,4,54,Femenino,7025897,13744270,1,21,Independiente,0.345776,No,9,38311001,760
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4995,63,NaN,696129,11440870,8,4,Independiente,0.120851,Sí,8,4076636,317
4996,4996,68,Femenino,4113865,4381028,4,4,Independiente,0.720181,No,4,30950058,464
4997,4997,25,Masculino,9286533,3945280,6,27,Independiente,0.049504,Sí,0,19088325,849
4998,4998,54,Masculino,4470369,10336483,1,28,Independiente,0.724321,Sí,3,17244935,722
4999,4999,43,Femenino,6622189,17174947,8,25,Desempleado,0.339645,Sí,8,39798659,318

In [ ]:
# Verificar si hay valores nulos
print(df.isnull().sum())

index                      0
Edad                       0
Género                    16
Ingreso_mensual            0
Saldo_total                0
Número_de_cuentas          0
Historial_crediticio       0
Tipo_de_empleo             0
Porcentaje_uso_credito     0
Mora_en_pagos              0
Número_de_moras            0
Monto_total_prestado       0
Puntaje_crediticio         0
dtype: int64

In [ ]:
# Ajustamos valores categóricos
df['Género'] = df['Género'].fillna('Desconocido')

In [ ]:
print(df.isnull().sum())

index                     0
Edad                      0
Género                    0
Ingreso_mensual           0
Saldo_total               0
Número_de_cuentas         0
Historial_crediticio      0
Tipo_de_empleo            0
Porcentaje_uso_credito    0
Mora_en_pagos             0
Número_de_moras           0
Monto_total_prestado      0
Puntaje_crediticio        0
dtype: int64

In [ ]:
#Codificación de Variables Categóricas

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Label Encoding para variables binarias
label_encoder = LabelEncoder()
df['Género'] = label_encoder.fit_transform(df['Género'])  # 'Masculino' -> 1, 'Femenino' -> 0
df['Mora_en_pagos'] = label_encoder.fit_transform(df['Mora_en_pagos'])  # 'Sí' -> 1, 'No' -> 0

# One-Hot Encoding para 'Tipo_de_empleo'
df = pd.get_dummies(df, columns=['Tipo_de_empleo'], drop_first=True)  # Evitar colinealidad eliminando una categoría

In [ ]:
df.head(5000)

,index,Edad,Género,Ingreso_mensual,Saldo_total,Número_de_cuentas,Historial_crediticio,Porcentaje_uso_credito,Mora_en_pagos,Número_de_moras,Monto_total_prestado,Puntaje_crediticio,Tipo_de_empleo_Empleado,Tipo_de_empleo_Independiente
0,0,63,1,1995089,9864628,5,12,0.551613,1,4,11261919,494,False,True
1,1,53,1,4063724,4092912,4,19,0.391506,1,4,190549,309,False,False
2,2,23,1,5210231,18200066,4,9,0.606219,0,6,29633064,563,False,False
3,3,22,1,9404231,6860855,1,14,0.605031,0,3,33700465,389,False,False
4,4,54,1,7025897,13744270,1,21,0.345776,0,9,38311001,760,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4995,63,0,696129,11440870,8,4,0.120851,1,8,4076636,317,False,True
4996,4996,68,1,4113865,4381028,4,4,0.720181,0,4,30950058,464,False,True
4997,4997,25,2,9286533,3945280,6,27,0.049504,1,0,19088325,849,False,True
4998,4998,54,2,4470369,10336483,1,28,0.724321,1,3,17244935,722,False,True
4999,4999,43,1,6622189,17174947,8,25,0.339645,1,8,39798659,318,False,False

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Separar las columnas numéricas
numeric_columns = ['Edad', 'Ingreso_mensual', 'Saldo_total', 'Número_de_cuentas',
                   'Historial_crediticio', 'Porcentaje_uso_credito',
                   'Número_de_moras', 'Monto_total_prestado']

# Escalado estándar (media=0, desviación estándar=1)
scaler = StandardScaler()
df[numeric_columns] = scaler.fit_transform(df[numeric_columns])

df.head(5000)

,index,Edad,Género,Ingreso_mensual,Saldo_total,Número_de_cuentas,Historial_crediticio,Porcentaje_uso_credito,Mora_en_pagos,Número_de_moras,Monto_total_prestado,Puntaje_crediticio,Tipo_de_empleo_Empleado,Tipo_de_empleo_Independiente
0,0,1.319651,1,-1.196644,-0.008105,0.029160,-0.356195,0.184077,1,-0.157041,-0.954787,494,False,True
1,1,0.646449,1,-0.439577,-1.013333,-0.357575,0.478768,-0.371844,1,-0.157041,-1.724238,309,False,False
2,2,-1.373157,1,-0.019985,1.443631,-0.357575,-0.714037,0.373680,0,0.542474,0.321993,563,False,False
3,3,-1.440477,1,1.514911,-0.531256,-1.517779,-0.117634,0.369552,0,-0.506798,0.604675,389,False,False
4,4,0.713769,1,0.644502,0.667590,-1.517779,0.717329,-0.530627,0,1.591745,0.925103,760,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4995,1.319651,0,-1.672030,0.266420,1.189364,-1.310439,-1.311606,1,1.241988,-1.454158,317,False,True
4996,4996,1.656252,1,-0.421227,-0.963153,-0.357575,-1.310439,0.769374,0,-0.157041,0.413524,464,False,True
4997,4997,-1.238517,2,1.471836,-1.039045,0.415894,1.433011,-1.559339,1,-1.556070,-0.410858,849,False,True
4998,4998,0.713769,2,-0.290756,0.074075,-1.517779,1.552292,0.783750,1,-0.506798,-0.538972,722,False,True
4999,4999,-0.026753,1,0.496755,1.265092,1.189364,1.194451,-0.551913,1,1.241988,1.028494,318,False,False

In [ ]:
# Alternativamente, usamos MinMaxScaler (valores entre 0 y 1)
min_max_scaler = MinMaxScaler()
df[numeric_columns] = min_max_scaler.fit_transform(df[numeric_columns])
df.head(5000)

,index,Edad,Género,Ingreso_mensual,Saldo_total,Número_de_cuentas,Historial_crediticio,Porcentaje_uso_credito,Mora_en_pagos,Número_de_moras,Monto_total_prestado,Puntaje_crediticio,Tipo_de_empleo_Empleado,Tipo_de_empleo_Independiente
0,0,0.882353,1,0.157222,0.493194,0.500,0.392857,0.551544,1,0.444444,0.225182,494,False,True
1,1,0.686275,1,0.375083,0.204563,0.375,0.642857,0.391393,1,0.444444,0.003698,309,False,False
2,2,0.098039,1,0.495829,0.910031,0.375,0.285714,0.606166,0,0.666667,0.592700,563,False,False
3,3,0.078431,1,0.937526,0.342981,0.000,0.464286,0.604977,0,0.333333,0.674069,389,False,False
4,4,0.705882,1,0.687049,0.687206,0.000,0.714286,0.345650,0,1.000000,0.766303,760,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4995,0.882353,0,0.020420,0.572018,0.875,0.107143,0.120663,1,0.888889,0.081439,317,False,True
4996,4996,0.980392,1,0.380364,0.218971,0.375,0.107143,0.720159,0,0.444444,0.619046,464,False,True
4997,4997,0.137255,2,0.925131,0.197180,0.625,0.928571,0.049295,1,0.000000,0.381751,849,False,True
4998,4998,0.705882,2,0.417909,0.516790,0.000,0.964286,0.724300,1,0.333333,0.344873,722,False,True
4999,4999,0.490196,1,0.644532,0.858767,0.875,0.857143,0.339518,1,0.888889,0.796064,318,False,False

In [ ]:
# Comprobación final del tipo de datos
print(df.dtypes)

index                             int64
Edad                            float64
Género                            int64
Ingreso_mensual                 float64
Saldo_total                     float64
Número_de_cuentas               float64
Historial_crediticio            float64
Porcentaje_uso_credito          float64
Mora_en_pagos                     int64
Número_de_moras                 float64
Monto_total_prestado            float64
Puntaje_crediticio                int64
Tipo_de_empleo_Empleado            bool
Tipo_de_empleo_Independiente       bool
dtype: object

In [ ]:
#Se prepara el análisis y modelado. con las siguientes transformaciones:

#1 Variables categóricas codificadas mediante Label Encoding y One-Hot Encoding.
#2 Variables numéricas escaladas utilizando StandardScaler.
#3 Todas las columnas innecesarias (como identificadores únicos o categorías redundantes) han sido eliminadas o transformadas.